# Day 13

## Create arrays with all the data types available in numpy

In [9]:
import numpy as np
num = np.array([5, 6, 7, 8], dtype = 'int_')
print(num)
print(num.dtype)

[5 6 7 8]
int32


In [3]:
num = np.array([True, False, False, True], dtype = 'bool_')
print(num)
print(num.dtype)

[ True False False  True]
bool


In [5]:
num = np.array([9.6, 2.1, 3.9, 4.8], dtype = 'float_')
print(num)
print(num.dtype)

[9.6 2.1 3.9 4.8]
float64


In [6]:
num = np.array([1+5j, 2+8j, 6+9.7j, 7+3.4j], dtype = 'complex_')
print(num)
print(num.dtype)

[1.+5.j  2.+8.j  6.+9.7j 7.+3.4j]
complex128


In [7]:
num = np.array(['p', 'q', 'r', 's'], dtype = 'S')
print(num)
print(num.dtype)

[b'p' b'q' b'r' b's']
|S1


In [11]:
num = np.array([[9, 3], [1.8, 1.9], ['Damon', 'Elena']], dtype = 'O')
print(num)
print(num.dtype)

[[9 3]
 [1.8 1.9]
 ['Damon' 'Elena']]
object


In [12]:
num = np.array([6, 7, 8, 9], dtype = 'U')
print(num)
print(num.dtype)

['6' '7' '8' '9']
<U1


In [14]:
num = np.array([1, 4, 3, 6], dtype = 'uint8')
print(num)
print(num.dtype)

[1 4 3 6]
uint8
